spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/group5?useSSL=false&serverTimezone=UTC
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  thymeleaf:
    cache: false

mybatis-plus:
  type-aliases-package: com.group5.Mapper # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.hmdp: debug